name: Build, Test and Deploy Java App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-dev:
    name: Build in Dev
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean compile

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: Test
    needs: build-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

      - name: Package the app
        run: mvn package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/java-project-repo-1.0.jar

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    environment:
      name: Prod
      url: https://java-project-webapp.azurewebsites.net
    needs: test

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'demo-java-project'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: java-project-repo-1.0.jar

      - name: Output Web App URL
        run: |
          echo App deployed at: https://java-project-webapp.azurewebsites.net

